### ISSUE TITLE
JSON data propagation

### ISSUE THREAD

**Issue by bill-luu** [UCSolarCarTeam/Epsilon-Dashboard#78]
Let Jeff explain

**Comment by jeffh1996** [comment]
Linked with #77. Any data that is received is not sent anywhere. The JsonReceiver class in the Communication Layer does not connect to any input (to receive the JSON data) and I am not sure if the output signals are correct or not since no signals are being sent. Ideally, the JSON data should be retrieved from the RabbitMQ(see #77) and then propagated throughout the system to the UI so that the UI is updated when new data is received.
